serviceMaps:
  serviceName: birth-services
  mappings:
    - version: 1.0
      description: Persists birthCertificate details in eg_birth_certificate_request  table
      fromTopic: save-birth-cert-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO public.eg_birth_certificate_request (id, registrationno, registrydetailsid, createdby, createdtime,lastmodifiedtime, lastmodifiedby, 
                filestoreid, status, additionaldetail, embeddedurl, dateofissue, tenantid,applicationid, ack_no, certificateno) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: birthCertificate
          jsonMaps:
            - jsonPath: $.birthCertificate.id

            - jsonPath: $.birthCertificate.registrtionNo

            - jsonPath: $.birthCertificate.registrationId

            - jsonPath: $.birthCertificate.auditDetails.createdBy

            - jsonPath: $.birthCertificate.auditDetails.createdTime

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.birthCertificate.filestoreid

            - jsonPath: $.birthCertificate.applicationStatus

            - jsonPath: $.birthCertificate.additionalDetail
              type: JSON
              dbType: JSONB

            - jsonPath: $.birthCertificate.embeddedUrl

            - jsonPath: $.birthCertificate.dateofissue

            - jsonPath: $.birthCertificate.tenantId

            - jsonPath: $.birthCertificate.applicationId

            - jsonPath: $.birthCertificate.applicationNumber

            - jsonPath: $.birthCertificate.birthCertificateNo


    - version: 1.0
      description: Update birthCertificate details in eg_birth_certificate_request  table
      fromTopic: update-birth-cert-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO eg_birth_certificate_request_audit SELECT * FROM eg_birth_certificate_request WHERE id = ?;
          basePath: birthCertificate
          jsonMaps:

            - jsonPath: $.birthCertificate.id

        - query: UPDATE eg_birth_certificate_request SET status = ?, filestoreid =?, embeddedurl = ? ,dateofissue =?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
          basePath: birthCertificate
          jsonMaps:

            - jsonPath: $.birthCertificate.applicationStatus

            - jsonPath: $.birthCertificate.filestoreid

            - jsonPath: $.birthCertificate.embeddedUrl

            - jsonPath: $.birthCertificate.dateofissue

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.birthCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.birthCertificate.id

    - version: 1.0
      description: Persists update birth details in eg_birth_details  table
      fromTopic: update-birth-application-payment-topic
      isTransaction: true
      queryMaps:
        - query: INSERT INTO eg_birth_details_audit SELECT * FROM eg_birth_details WHERE applicationno = ?;
          basePath: PaymentDetails.*
          jsonMaps:
                - jsonPath: $.PaymentDetails.*.applicationNumber

        - query: UPDATE public.eg_birth_details SET action=?, status=?, has_payment=?, is_payment_success=?, amount=?, lastmodifiedby=?,  lastmodifiedtime=? WHERE applicationno=?;
          basePath: PaymentDetails.*
          jsonMaps:
                - jsonPath: $.PaymentDetails.*.action

                - jsonPath: $.PaymentDetails.*.applicationStatus

                - jsonPath: $.PaymentDetails.*.hasPayment

                - jsonPath: $.PaymentDetails.*.isPaymentSuccess

                - jsonPath: $.PaymentDetails.*.amount

                - jsonPath: $.PaymentDetails.*.auditDetails.lastModifiedBy

                - jsonPath: $.PaymentDetails.*.auditDetails.lastModifiedTime

                - jsonPath: $.PaymentDetails.*.applicationNumber
