serviceMaps:
  serviceName: birth-services
  mappings:
    - version: 1.0
      description: Persists nacCertificate details in eg_nac_certificate_request  table
      fromTopic: save-nac-cert-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO public.eg_nac_certificate_request (id, registrationno, registrydetailsid, createdby, createdtime,lastmodifiedtime, lastmodifiedby, 
                filestoreid, status, additionaldetail, embeddedurl, dateofissue, tenantid,applicationid, ack_no, certificateno) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: nacCertificate
          jsonMaps:
            - jsonPath: $.nacCertificate.id

            - jsonPath: $.nacCertificate.registrtionNo

            - jsonPath: $.nacCertificate.registrationId

            - jsonPath: $.nacCertificate.auditDetails.createdBy

            - jsonPath: $.nacCertificate.auditDetails.createdTime

            - jsonPath: $.nacCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.nacCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.nacCertificate.filestoreid

            - jsonPath: $.nacCertificate.applicationStatus

            - jsonPath: $.nacCertificate.additionalDetail
              type: JSON
              dbType: JSONB

            - jsonPath: $.nacCertificate.embeddedUrl

            - jsonPath: $.nacCertificate.dateofissue

            - jsonPath: $.nacCertificate.tenantId

            - jsonPath: $.nacCertificate.applicationId

            - jsonPath: $.nacCertificate.applicationNumber

            - jsonPath: $.nacCertificate.nacCertificateNo


    - version: 1.0
      description: Update nacCertificate details in eg_nac_certificate_request  table
      fromTopic: update-nac-cert-topic
      isTransaction: true
      queryMaps:

        - query: INSERT INTO eg_nac_certificate_request_audit SELECT * FROM eg_nac_certificate_request WHERE id = ?;
          basePath: nacCertificate
          jsonMaps:

            - jsonPath: $.nacCertificate.id

        - query: UPDATE eg_nac_certificate_request SET status = ?, filestoreid =?, embeddedurl = ? ,dateofissue =?, lastmodifiedby = ?,  lastmodifiedtime = ? WHERE id=?;
          basePath: nacCertificate
          jsonMaps:

            - jsonPath: $.nacCertificate.applicationStatus

            - jsonPath: $.nacCertificate.filestoreid

            - jsonPath: $.nacCertificate.embeddedUrl

            - jsonPath: $.nacCertificate.dateofissue

            - jsonPath: $.nacCertificate.auditDetails.lastModifiedBy

            - jsonPath: $.nacCertificate.auditDetails.lastModifiedTime

            - jsonPath: $.nacCertificate.id

 
