serviceMaps:
 serviceName: tl-services
 mappings:
 - version: 1.0
   description: Persists tradeLicense Correction details in eg_tl_correction  table
   fromTopic: savecorrection-tl-tradelicense
   isTransaction: true
   queryMaps:

       - query: INSERT INTO eg_tl_correction(id, tenantid, tradelicenseid, tradelicensedetailid, licensenumber, correctionappnumber, correction, history, correctionstatus, active, createdby, lastmodifiedby, createdtime, lastmodifiedtime, applicationType, workflowCode, action) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: LicenseCorrection.*
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.id

          - jsonPath: $.LicenseCorrection.*.tenantId

          - jsonPath: $.LicenseCorrection.*.tradeLicenseId

          - jsonPath: $.LicenseCorrection.*.tradeLicenseDetailId

          - jsonPath: $.LicenseCorrection.*.licenseNumber

          - jsonPath: $.LicenseCorrection.*.applicationNumber

          - jsonPath: $.LicenseCorrection.*.correction
            type: JSON

            dbType: JSONB

          - jsonPath: $.LicenseCorrection.*.history
            type: JSON

            dbType: JSONB

          - jsonPath: $.LicenseCorrection.*.status

          - jsonPath: $.LicenseCorrection.*.active

          - jsonPath: $.LicenseCorrection.*.auditDetails.createdBy

          - jsonPath: $.LicenseCorrection.*.auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection.*.auditDetails.createdTime

          - jsonPath: $.LicenseCorrection.*.auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.applicationType

          - jsonPath: $.LicenseCorrection.*.workflowCode

          - jsonPath: $.LicenseCorrection.*.action


       - query: INSERT INTO eg_tl_applicationdocument( id, tenantid, active, documenttype, tradecategorydetail, filestoreid, tradelicensedetailid, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
         basePath: LicenseCorrection.*.applicationDocuments.*
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.applicationDocuments.*.id

          - jsonPath: $.LicenseCorrection.*.applicationDocuments.*.tenantId

          - jsonPath: $.LicenseCorrection.*.applicationDocuments.*.active

          - jsonPath: $.LicenseCorrection.*.applicationDocuments.*.documentType

          - jsonPath: $.LicenseCorrection.*.applicationDocuments.*.tradecategorydetail

          - jsonPath: $.LicenseCorrection.*.applicationDocuments.*.fileStoreId

          - jsonPath: $.LicenseCorrection[*][?({id} in @.applicationDocuments[*].id)].tradeLicenseDetailId

          - jsonPath: $.LicenseCorrection[*][?({id} in @.applicationDocuments[*].id)].auditDetails.createdBy

          - jsonPath: $.LicenseCorrection[*][?({id} in @.applicationDocuments[*].id)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({id} in @.applicationDocuments[*].id)].auditDetails.createdTime

          - jsonPath: $.LicenseCorrection[*][?({id} in @.applicationDocuments[*].id)].auditDetails.lastModifiedTime


 - version: 1.0
   description: Update workflow and approved correction details in License tables
   fromTopic: updatecorrection-tl-tradelicense
   isTransaction: true
   queryMaps:

       - query: UPDATE eg_tl_correction SET correctionstatus = ?, assignee=?, lastmodifiedby = ?,  lastmodifiedtime = ?, iscurrentrequest=?, action = ?  WHERE id=?;
         basePath: LicenseCorrection.*
         jsonMaps:

          - jsonPath: $.LicenseCorrection.*.status

          - jsonPath: $.LicenseCorrection.*.assignUser

          - jsonPath: $.LicenseCorrection.*.auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection.*.auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.isCurrentRequest

          - jsonPath: $.LicenseCorrection.*.action

          - jsonPath: $.LicenseCorrection.*.id


       - query: UPDATE eg_tl_tradelicense SET tradeName = ?, licenseunitnamelocal = ?  WHERE id=?;
         basePath: LicenseCorrection.*.licenseUnitUpdate
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.licenseUnitUpdate.licenseUnitName

          - jsonPath: $.LicenseCorrection.*.licenseUnitUpdate.licenseUnitNameLocal

          - jsonPath: $.LicenseCorrection.*.licenseUnitUpdate.tradeLicenseUpdateId


       - query: INSERT INTO eg_tl_tradeunit(id, tenantid, active, businesscategory, businesstype, businesssubtype, tradelicensedetailid, createdby, lastmodifiedby, createdtime, lastmodifiedtime)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE SET active = ?, businesscategory = ?, businesstype = ?, businesssubtype = ?,  lastmodifiedby = ?,  lastmodifiedtime = ?;
         basePath: LicenseCorrection.*.tradeNewUpdate.*
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.tradeUnitId

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.tenantId

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.active

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.businessCategory

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.businessType

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.businessSubtype

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].tradeLicenseDetailId

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].auditDetails.createdBy

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].auditDetails.createdTime

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.active

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.businessCategory

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.businessType

          - jsonPath: $.LicenseCorrection.*.tradeNewUpdate.*.businessSubtype

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({tradeUnitId} in @.tradeNewUpdate[*].tradeUnitId)].auditDetails.lastModifiedTime


       - query: UPDATE eg_tl_tradeunit SET active=? WHERE id=?;
         basePath: LicenseCorrection.*.tradeDelete.*
         jsonMaps:

          - jsonPath: $.LicenseCorrection.*.tradeDelete.*.active

          - jsonPath: $.LicenseCorrection.*.tradeDelete.*.tradeUnitId


       - query: INSERT INTO eg_tl_structureplacedetail(id, tenantid, blockno, surveyno, subdivisionno, partitionno, doorno, doorsub, buildingid, vehicleno, vesselno, tradelicensedetailid, active, createdby, lastmodifiedby, createdtime, lastmodifiedtime, isresurveyed, stallno) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,?) ON CONFLICT (id) DO UPDATE SET blockno=?, surveyno=?, subdivisionno=?, partitionno=?, doorno=?, doorsub=?, buildingid=?, vehicleno=?, vesselno=?, active=?, lastmodifiedby=?, lastmodifiedtime=?, isresurveyed=?, stallno = ?;
         basePath: LicenseCorrection.*.structureAddUpdate.*
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.structureId

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.tenantId

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.blockNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.surveyNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.subDivisionNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.partitionNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.doorNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.doorNoSub

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.buildingId

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.vehicleNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.vesselNo

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].tradeLicenseDetailId

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.active

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].auditDetails.createdBy

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].auditDetails.createdTime

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.isResurveyed

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.stallNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.blockNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.surveyNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.subDivisionNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.partitionNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.doorNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.doorNoSub

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.buildingId

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.vehicleNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.vesselNo

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.active

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({structureId} in @.structureAddUpdate[*].structureId)].auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.isResurveyed

          - jsonPath: $.LicenseCorrection.*.structureAddUpdate.*.stallNo


       - query: UPDATE eg_tl_structureplacedetail SET active=? WHERE id=?;
         basePath: LicenseCorrection.*.structureDelete.*
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.structureDelete.*.active

          - jsonPath: $.LicenseCorrection.*.structureDelete.*.structureId


       - query: INSERT INTO eg_tl_owner(id, tenantid,active, tradelicensedetailid, ownername, aadharno, email, createdby,lastmodifiedby, createdtime, lastmodifiedtime, ownernamelocal, careof, careofname, designation, housename, street, locality, postoffice, pincode, ownercontactno) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT ON CONSTRAINT pk_eg_tl_owner DO UPDATE SET active = ?, ownername = ?, aadharno = ?, email = ?, lastmodifiedby = ?,  lastmodifiedtime = ?, ownernamelocal = ?, careof = ?, careofname = ?, designation = ?, housename = ?, street = ?, locality = ?, postoffice = ?, pincode = ?, ownercontactno = ?;
         basePath: LicenseCorrection.*.ownerAddUpdate.*
         jsonMaps:
          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.uuid

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.tenantId

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.userActive

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].tradeLicenseDetailId

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.name

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.aadhaarNumber

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.emailId

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].auditDetails.createdBy

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].auditDetails.createdTime

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.applicantNameLocal

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.careOf

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.careOfName

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.designation

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.houseName

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.street

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.locality

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.postOffice

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.pincode

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.mobileNumber

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.userActive

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.name

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.aadhaarNumber

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.emailId

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].auditDetails.lastModifiedBy

          - jsonPath: $.LicenseCorrection[*][?({id} in @.ownerAddUpdate[*].id)].auditDetails.lastModifiedTime

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.applicantNameLocal

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.careOf

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.careOfName

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.designation

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.houseName

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.street

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.locality

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.postOffice

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.pincode

          - jsonPath: $.LicenseCorrection.*.ownerAddUpdate.*.mobileNumber


       - query: UPDATE eg_tl_owner SET active=? WHERE id=? and tradelicensedetailid=?;
         basePath: LicenseCorrection.*.ownerDelete.*
         jsonMaps:

          - jsonPath: $.LicenseCorrection.*.ownerDelete.*.userActive

          - jsonPath: $.LicenseCorrection.*.ownerDelete.*.uuid

          - jsonPath: $.LicenseCorrection.*.ownerDelete.*.tradeLicenseDetailDelId
      

